# Generated by Django 5.1.2 on 2024-10-25 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid_time',
        ),
    ]
