# Generated by Django 5.1.2 on 2024-11-01 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auction_expired'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='price',
            new_name='starting_bid',
        ),
    ]
