# Generated by Django 5.1.2 on 2024-10-25 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_auction_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='auction_item',
            new_name='auction',
        ),
    ]
