# Generated by Django 5.1.2 on 2024-10-25 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_rename_auction_item_bid_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='highest_bidder',
        ),
        migrations.AddField(
            model_name='auction',
            name='highest_bid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highest_bid', to='marketplace.bid'),
        ),
    ]
