# Generated by Django 5.1.2 on 2024-10-25 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_remove_auction_highest_bidder_auction_highest_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='auction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='marketplace.auction'),
        ),
    ]
