# Generated by Django 5.1 on 2024-08-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_item_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='item',
            new_name='item_id',
        ),
    ]
